### ISSUE TITLE
Tests on wildcard support for domain.* TLD matching

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/TestCases#25]
See here:
https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/421

I think we should simply extend the "Simple rules" tests and add a couple more tests there.

Check what products support them:

1. Android, Win, Mac -- will support them when the new CoreLibs version is available.
2. Chrome/FF extensions -- should already support this
3. iOS/Safari -- we should add support for these rules: https://github.com/AdguardTeam/AdGuardForSafari/issues/248

**Comment by tvinzz** [comment]
http://smp01.surge.sh/
Simple rules test -> testcases 5 and 6
