### ISSUE TITLE
Test resource mismatch

### ISSUE THREAD

**Issue by ngorskikh** [AdguardTeam/TestCases#45]
The content of the test resource here:
https://github.com/AdguardTeam/TestCases/blob/c130b93660eb9a7ed1b27dce3ee4d7e01c226cc6/public/Userscripts/apiTester/resource.js#L1
Doesn't match the assertion here:
https://github.com/AdguardTeam/TestCases/blob/c130b93660eb9a7ed1b27dce3ee4d7e01c226cc6/public/Userscripts/apiTester/api-tester.user.js#L109

**Comment by sxgunchenko** [comment]
Also, after the linter run there is an issue with the $replace rules tests:
![image](https://user-images.githubusercontent.com/26045362/113876121-1b272f80-97c0-11eb-8d08-337330a58582.png)
