### ISSUE TITLE
Script rules for the firefox browser

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/TestCases#51]
1. **Add tests to check that script rules added with custom filters are not working in the firefox browser**
2. **Fix testcase**
```
    QUnit.test('2. Test script rule exception', (assert) => {
        assert.ok(adgCheck && !window.__testCase2);
    });
```
Test should check that `__testCase2` is not changing, currently it doesn't work correctly because `.__testCase2` is `undefined` by default.

**Comment by tvinzz** [comment]
1. added
2. fixed
